services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Janolaw\Janolawservice\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
  cache.janolawservices:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: [ '@TYPO3\CMS\Core\Cache\CacheManager', 'getCache' ]
    arguments: [ 'janolaw_janolawservices' ]

  Janolaw\Janolawservice\Controller\JanolawServiceController:
    public: true
    arguments:
      $cache: '@cache.janolawservices'

